#!/usr/bin/env bash
sudo gem install fir-cli
echo "APPCENTER_OUTPUT_DIRECTORY" $APPCENTER_OUTPUT_DIRECTORY 'APP_FILE' $APP_FILE 'FIR_TOKEN' $FIR_TOKEN

fir p $APPCENTER_OUTPUT_DIRECTORY/$APP_FILE -T $FIR_TOKEN
